In [1]:
# Testing for required packages

import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check PyTorch access (should print out a tensor)
print(torch.randn(3, 3))

# Check for GPU (should return True)
print(torch.cuda.is_available())

tensor([[-0.4056,  1.3384, -1.3961],
        [ 1.4582, -1.3275,  0.1073],
        [ 0.0046,  0.1541, -0.1120]])
True


In [11]:
import torch
print(torch.__version__)

2.5.1


In [12]:
# More about tensors: https://pytorch.org/docs/stable/tensors.html

scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [18]:
scalar.ndim

0

In [19]:
# Get tensor back as Python int
scalar.item()

7

In [21]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [22]:
vector.shape

torch.Size([2])

In [25]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [27]:
#MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [28]:
MATRIX.shape

torch.Size([2, 2])

In [33]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5],
                        [4, 5, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [4, 5, 6]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape

torch.Size([1, 4, 3])

In [36]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5],
        [4, 5, 6]])

In [40]:
# Random tensors
# Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
# Torch random tensors: https://pytorch.org/docs/main/generated/torch.rand.html

# Create a random tensor of size (3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.1023, 0.8914, 0.4446, 0.8655],
         [0.4312, 0.8294, 0.2635, 0.3456],
         [0.8555, 0.3691, 0.0330, 0.0853]],

        [[0.3483, 0.8226, 0.1097, 0.5936],
         [0.5458, 0.4432, 0.0282, 0.8603],
         [0.9080, 0.2644, 0.9969, 0.2431]]])

In [41]:
random_tensor.ndim

3

In [39]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B) << color can go at the front
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [42]:
# Create tensors of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [44]:
# Create tensors of all ones
# Tensor of all zeros or ones can work as a mask
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
ones.dtype

torch.float32

In [46]:
random_tensor.dtype

torch.float32

In [50]:
# Creating a range of tensors
# Torch arange: https://pytorch.org/docs/stable/generated/torch.arange.html
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# Will there be ones_like?
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
# Float 32 tensor
# datatype: the datatype of the tensor (e.g. float32 or float16)
# device: what device is your tensor is on
# requires_grad: whether or not to track gradients with this tensors operation
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [61]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [62]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [63]:
# Check the data types
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [64]:
# Getting information from tensors
# 1. Tensors not right datatype - can use tensor.dtype
# 2. Tensors not right shape - can use tensor.shape
# 3. Tensors not on the right device - can use tensor.device

In [70]:
# Create a tensor
some_tensor = torch.rand(5, 7, dtype=torch.float64)

In [71]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # .size is a function, .shape is an attribute
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3388, 0.1346, 0.8042, 0.0343, 0.3684, 0.6713, 0.8391],
        [0.0917, 0.1986, 0.1583, 0.3875, 0.8975, 0.9349, 0.9814],
        [0.9996, 0.2134, 0.4213, 0.9390, 0.2977, 0.6272, 0.7558],
        [0.7124, 0.2887, 0.7410, 0.4768, 0.9295, 0.4144, 0.2718],
        [0.1642, 0.2163, 0.5426, 0.7112, 0.1655, 0.2471, 0.5205]],
       dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([5, 7])
Device tensor is on: cpu


In [72]:
# Manipulating tensors (tensor operations)
# Operations: Addition, Subtraction, Multiplication (element-wise), Division, Matrix Multiplication

In [73]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [74]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [75]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [78]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [80]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [81]:
#

In [82]:
# Element wise multiplication
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [83]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [84]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 999 µs


In [85]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [93]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm is the same as torch.matmul (alias)
# torch.mm(tensor_A, tensor_B) << Shape error

# We can manipulate the shape of one of out tensors using transpose

In [94]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [95]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [96]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"Original shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
Original shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
