In [1]:
# Testing for required packages

import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check PyTorch access (should print out a tensor)
print(torch.randn(3, 3))

# Check for GPU (should return True)
print(torch.cuda.is_available())

tensor([[-0.4056,  1.3384, -1.3961],
        [ 1.4582, -1.3275,  0.1073],
        [ 0.0046,  0.1541, -0.1120]])
True


In [2]:
import torch
print(torch.__version__)

2.5.1


In [12]:
# More about tensors: https://pytorch.org/docs/stable/tensors.html

scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [18]:
scalar.ndim

0

In [19]:
# Get tensor back as Python int
scalar.item()

7

In [21]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [22]:
vector.shape

torch.Size([2])

In [25]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [27]:
#MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [28]:
MATRIX.shape

torch.Size([2, 2])

In [33]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5],
                        [4, 5, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [4, 5, 6]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape

torch.Size([1, 4, 3])

In [36]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5],
        [4, 5, 6]])

In [40]:
# Random tensors
# Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
# Torch random tensors: https://pytorch.org/docs/main/generated/torch.rand.html

# Create a random tensor of size (3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.1023, 0.8914, 0.4446, 0.8655],
         [0.4312, 0.8294, 0.2635, 0.3456],
         [0.8555, 0.3691, 0.0330, 0.0853]],

        [[0.3483, 0.8226, 0.1097, 0.5936],
         [0.5458, 0.4432, 0.0282, 0.8603],
         [0.9080, 0.2644, 0.9969, 0.2431]]])

In [41]:
random_tensor.ndim

3

In [39]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B) << color can go at the front
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [42]:
# Create tensors of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [44]:
# Create tensors of all ones
# Tensor of all zeros or ones can work as a mask
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
ones.dtype

torch.float32

In [46]:
random_tensor.dtype

torch.float32

In [50]:
# Creating a range of tensors
# Torch arange: https://pytorch.org/docs/stable/generated/torch.arange.html
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# Will there be ones_like?
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
# Float 32 tensor
# datatype: the datatype of the tensor (e.g. float32 or float16)
# device: what device is your tensor is on
# requires_grad: whether or not to track gradients with this tensors operation
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [61]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [62]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [63]:
# Check the data types
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [64]:
# Getting information from tensors
# 1. Tensors not right datatype - can use tensor.dtype
# 2. Tensors not right shape - can use tensor.shape
# 3. Tensors not on the right device - can use tensor.device

In [70]:
# Create a tensor
some_tensor = torch.rand(5, 7, dtype=torch.float64)

In [71]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # .size is a function, .shape is an attribute
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3388, 0.1346, 0.8042, 0.0343, 0.3684, 0.6713, 0.8391],
        [0.0917, 0.1986, 0.1583, 0.3875, 0.8975, 0.9349, 0.9814],
        [0.9996, 0.2134, 0.4213, 0.9390, 0.2977, 0.6272, 0.7558],
        [0.7124, 0.2887, 0.7410, 0.4768, 0.9295, 0.4144, 0.2718],
        [0.1642, 0.2163, 0.5426, 0.7112, 0.1655, 0.2471, 0.5205]],
       dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([5, 7])
Device tensor is on: cpu


In [72]:
# Manipulating tensors (tensor operations)
# Operations: Addition, Subtraction, Multiplication (element-wise), Division, Matrix Multiplication

In [73]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [74]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [75]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [78]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [80]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [81]:
#

In [82]:
# Element wise multiplication
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [83]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [84]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 999 µs


In [85]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [93]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm is the same as torch.matmul (alias)
# torch.mm(tensor_A, tensor_B) << Shape error

# We can manipulate the shape of one of out tensors using transpose

In [94]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [95]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [96]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"Original shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
Original shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [3]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [5]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [7]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # need floating point or complex dtype

(tensor(45.), tensor(45.))

In [8]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [9]:
# Find the positional min and max
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [10]:
# Reshaping - reshapes an input tensor to a defined shape
# View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
# Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
# Squeez - remove all '1' dimensions froom a tensor
# Unsqueeze - add a '1' dimension to a target tensor
# Permute - return a view of the input with dimensions permuted in a certain way

In [19]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [20]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [21]:
# Change the view
z = x.view(1, 9) # view shares the same memory with the original - changing z changes x
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [28]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
# dim for the direction of stacking, dim=0 for vstack, dim=1 for hstack
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [33]:
# Squeeze removes all single dimensions from a target tensor (e.g. 1 1 9 -> 9)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [35]:
# Unsqueeze adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) # dim for the position of added dimension
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [58]:
# Permute rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [60]:
# Permute uses view, which shares memory between the permuted and the original
x_original[1, 0, 0] = 98723497
print(x_original[1, 0, 0])
x_permuted = x_original.permute(2, 0, 1)
print(x_permuted[1, 0, 0])
print(x_permuted[0, 1, 0])

tensor(98723496.)
tensor(0.1904)
tensor(98723496.)


In [61]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [62]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [64]:
# Let's index on the most inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [65]:
# You can also use ":" to select "all" of a targhet dimension
x[:, 0]

tensor([[1, 2, 3]])

In [66]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [67]:
# Get all values of the 0th dimension but only the 1st index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [68]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [73]:
# Index on x to return 9
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


In [77]:
# NumPy array to tensor: torch.from_numpy, .numpy()
# https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # NumPy default dtype is float64, reflected by PyTorch when used
# tensor = torch.from_numpy(array).type(torch.float32) << this will change dtype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [78]:
# Change the value of array, what will this do to 'tensor'?

array = array + 1
array, tensor # Doesn't share memory

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [79]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # PyTorch default dtype is float32, reflected by NumPy when used
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor # Doesn't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [83]:
# Reproducibility (trying to take random out of random)
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4946, 0.9831, 0.5134, 0.2580],
        [0.5002, 0.6152, 0.6283, 0.6972],
        [0.5420, 0.5651, 0.0891, 0.8486]])
tensor([[0.1901, 0.3035, 0.6512, 0.4057],
        [0.8156, 0.6753, 0.9405, 0.6498],
        [0.6329, 0.6110, 0.1847, 0.5707]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [82]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 77

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [84]:
# Reproducibility in PyTorch: https://pytorch.org/docs/stable/notes/randomness.html
# Concepts of random seed in computer science

In [87]:
# CUDA semantics: https://pytorch.org/docs/stable/notes/cuda.html
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [88]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [89]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [90]:
# Moving tensors back to the CPU (NumPy only works on CPU)
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)